//! Minimal localhost HTTP/1.1 client.
//!
//! The data-management commands (backup, restore) call psycheros's
//! `/api/admin/entity-data/{export,import}` endpoints on `127.0.0.1`.
//! The full `reqwest` stack (TLS, tokio, hyper) is overkill for a
//! single localhost client; this module hand-rolls just enough of
//! HTTP/1.1 to do the job, with zero new dependencies.
//!
//! ## Scope and assumptions
//!
//! - `127.0.0.1` only. No TLS, no proxies, no DNS resolution.
//! - HTTP/1.1 with `Connection: close` (we always close after each
//!   request — no keepalive complexity).
//! - Server is expected to set `Content-Length` on every response.
//!   Psycheros's [`server.ts`] does this for all the routes we hit;
//!   we don't implement chunked transfer-encoding because we don't
//!   need to.
//! - Response body is read into memory up to a 2 GB cap (see
//!   [`MAX_BODY_BYTES`]). The entity data export is bounded by what
//!   an entity has accumulated over weeks/months — realistically tens
//!   of MB.
//!
//! If any of these assumptions stops holding (psycheros switches to
//! chunked encoding, the launcher needs to talk to a non-localhost
//! endpoint, etc.), prefer adding `reqwest` or `ureq` to expanding
//! this module — handwritten HTTP grows brittle fast outside its
//! original scope.

use std::io::{Read, Write};
use std::net::{SocketAddr, TcpStream};
use std::time::Duration;

/// One HTTP response we know what to do with. Generated by the
/// request helpers; consumers care about status + body.
#[derive(Debug)]
pub struct Response {
    pub status: u16,
    pub body: Vec<u8>,
}

impl Response {
    /// True when status is 2xx — used as the high-level "did the
    /// daemon accept my request" check throughout this crate.
    pub fn is_success(&self) -> bool {
        (200..300).contains(&self.status)
    }
}

/// Cap on response body size. Bigger than a realistic entity export
/// (tens of MB at the upper end) but bounded so a malformed response
/// can't make the launcher OOM.
const MAX_BODY_BYTES: usize = 4 * 1024 * 1024 * 1024 / 2; // 2 GB

/// Default connect + read timeouts. The export endpoint can take many
/// seconds on a large entity (recursive walk + zip compression), so
/// we err on the side of long timeouts rather than spurious failures.
const CONNECT_TIMEOUT: Duration = Duration::from_secs(5);
const READ_TIMEOUT: Duration = Duration::from_secs(300);

/// Send an HTTP/1.1 request to `127.0.0.1:<port>` and return the
/// fully-read response.
///
/// `method` is the verb (e.g. `"POST"`). `path` is the request path
/// starting with `/`. `body` is the raw request body (empty slice
/// for no body). `content_type` is set on the request when non-empty.
pub fn request_localhost(
    port: u16,
    method: &str,
    path: &str,
    body: &[u8],
    content_type: &str,
) -> std::io::Result<Response> {
    let addr: SocketAddr = format!("127.0.0.1:{port}").parse().map_err(|e| {
        std::io::Error::new(std::io::ErrorKind::InvalidInput, format!("bad addr: {e}"))
    })?;
    let mut stream = TcpStream::connect_timeout(&addr, CONNECT_TIMEOUT)?;
    stream.set_read_timeout(Some(READ_TIMEOUT))?;
    stream.set_write_timeout(Some(READ_TIMEOUT))?;

    let mut header = format!(
        "{method} {path} HTTP/1.1\r\n\
         Host: 127.0.0.1:{port}\r\n\
         Connection: close\r\n\
         Content-Length: {}\r\n",
        body.len(),
    );
    if !content_type.is_empty() {
        header.push_str(&format!("Content-Type: {content_type}\r\n"));
    }
    header.push_str("\r\n");

    stream.write_all(header.as_bytes())?;
    if !body.is_empty() {
        stream.write_all(body)?;
    }
    stream.flush()?;

    read_response(&mut stream)
}

/// Read a complete HTTP/1.1 response off the stream. Parses the
/// status line + headers, then reads exactly `Content-Length` bytes
/// of body. Errors if Content-Length is missing — see module doc.
fn read_response(stream: &mut TcpStream) -> std::io::Result<Response> {
    // Read into a growing buffer until we see the header terminator.
    // The buffer doubles as the body-prefix carrier — any bytes after
    // the `\r\n\r\n` belong to the body.
    let mut buf: Vec<u8> = Vec::with_capacity(8192);
    let mut chunk = [0u8; 4096];
    let header_end_idx = loop {
        let n = stream.read(&mut chunk)?;
        if n == 0 {
            return Err(std::io::Error::new(
                std::io::ErrorKind::UnexpectedEof,
                "connection closed before response headers complete",
            ));
        }
        buf.extend_from_slice(&chunk[..n]);
        if let Some(i) = find_header_terminator(&buf) {
            break i;
        }
        if buf.len() > 64 * 1024 {
            return Err(std::io::Error::new(
                std::io::ErrorKind::InvalidData,
                "response headers exceeded 64 KB",
            ));
        }
    };

    let header_bytes = &buf[..header_end_idx];
    let header_text = std::str::from_utf8(header_bytes)
        .map_err(|_| std::io::Error::new(std::io::ErrorKind::InvalidData, "non-UTF-8 headers"))?;
    let (status, content_length) = parse_status_and_length(header_text)?;

    // Body starts at header_end_idx + 4 (the `\r\n\r\n`). Anything
    // already in `buf` past that point is part of the body — we
    // carry it forward, then read the remaining bytes from the
    // socket up to the advertised content_length.
    let body_start = header_end_idx + 4;
    let body_in_buffer = buf.len().saturating_sub(body_start);
    if content_length > MAX_BODY_BYTES {
        return Err(std::io::Error::new(
            std::io::ErrorKind::InvalidData,
            format!("response body too large ({content_length} bytes)"),
        ));
    }
    let mut body = Vec::with_capacity(content_length);
    body.extend_from_slice(&buf[body_start..]);

    while body.len() < content_length {
        let need = content_length - body.len();
        let take = need.min(chunk.len());
        let n = stream.read(&mut chunk[..take])?;
        if n == 0 {
            return Err(std::io::Error::new(
                std::io::ErrorKind::UnexpectedEof,
                format!(
                    "connection closed mid-body ({}/{} bytes)",
                    body.len(),
                    content_length
                ),
            ));
        }
        body.extend_from_slice(&chunk[..n]);
    }

    let _ = body_in_buffer; // pre-allocated; the prefix is already in `body`.
    Ok(Response { status, body })
}

/// Find the `\r\n\r\n` separator between headers and body. Returns
/// the index of the first `\r`. Slow O(n) scan — fine for our use
/// case (headers are <64 KB).
fn find_header_terminator(buf: &[u8]) -> Option<usize> {
    buf.windows(4).position(|w| w == b"\r\n\r\n")
}

/// Pull status code + Content-Length out of the response header
/// block. Status line is `HTTP/1.1 <code> <reason>`; Content-Length
/// is a case-insensitive header. Returns
/// `(status, content_length_bytes)`.
fn parse_status_and_length(headers: &str) -> std::io::Result<(u16, usize)> {
    let mut lines = headers.split("\r\n");
    let status_line = lines
        .next()
        .ok_or_else(|| std::io::Error::new(std::io::ErrorKind::InvalidData, "empty response"))?;
    // "HTTP/1.1 200 OK"
    let mut parts = status_line.splitn(3, ' ');
    parts.next(); // version
    let status_str = parts.next().ok_or_else(|| {
        std::io::Error::new(std::io::ErrorKind::InvalidData, "malformed status line")
    })?;
    let status: u16 = status_str.parse().map_err(|_| {
        std::io::Error::new(std::io::ErrorKind::InvalidData, "non-numeric status code")
    })?;

    let mut content_length: Option<usize> = None;
    for line in lines {
        if let Some(value) = line
            .split_once(':')
            .filter(|(k, _)| k.eq_ignore_ascii_case("content-length"))
            .map(|(_, v)| v.trim())
        {
            content_length = value.parse().ok();
        }
    }
    let content_length = content_length.ok_or_else(|| {
        std::io::Error::new(
            std::io::ErrorKind::InvalidData,
            "response missing Content-Length header",
        )
    })?;
    Ok((status, content_length))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parses_status_and_length_ok() {
        let headers = "HTTP/1.1 200 OK\r\nContent-Length: 42\r\nContent-Type: application/json";
        let (status, len) = parse_status_and_length(headers).unwrap();
        assert_eq!(status, 200);
        assert_eq!(len, 42);
    }

    #[test]
    fn parses_404() {
        let headers = "HTTP/1.1 404 Not Found\r\nContent-Length: 9";
        let (status, len) = parse_status_and_length(headers).unwrap();
        assert_eq!(status, 404);
        assert_eq!(len, 9);
    }

    #[test]
    fn rejects_missing_content_length() {
        let headers = "HTTP/1.1 200 OK\r\nContent-Type: text/plain";
        let err = parse_status_and_length(headers).unwrap_err();
        assert_eq!(err.kind(), std::io::ErrorKind::InvalidData);
    }

    #[test]
    fn content_length_is_case_insensitive() {
        let headers = "HTTP/1.1 200 OK\r\ncontent-length: 7";
        let (_status, len) = parse_status_and_length(headers).unwrap();
        assert_eq!(len, 7);
    }

    #[test]
    fn finds_header_terminator() {
        let buf = b"GET / HTTP/1.1\r\nHost: x\r\n\r\nhello";
        let idx = find_header_terminator(buf).unwrap();
        // idx points at the start of the `\r\n\r\n` separator; the body
        // begins 4 bytes later.
        assert_eq!(&buf[idx..idx + 4], b"\r\n\r\n");
        assert_eq!(&buf[idx + 4..], b"hello");
    }
}
